/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes_1002949_5[] = { 0, 11, 22 };

// (before - mean) / scale
const float ei_classifier_anom_scale_1002949_5[3] = { 605.5633864751953, 616.8211458557544, 873.2879650431977 };
const float ei_classifier_anom_mean_1002949_5[3] = { 866.9100436697117, 593.992816872744, 3311.1176228061145 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters_1002949_5[32] = {
	{ ( float[3] ) { 1.0240126848220825, 1.5388637781143188, 2.14361310005188 }, 0.6452899799226042 },
	{ ( float[3] ) { 0.4250440001487732, 0.8854236006736755, 0.6590079069137573 }, 0.37114367830556905 },
	{ ( float[3] ) { -1.3467637300491333, -0.9156109690666199, -0.673920750617981 }, 0.13657459015686516 },
	{ ( float[3] ) { 1.039149522781372, 1.4679213762283325, 1.7959480285644531 }, 0.408004558614227 },
	{ ( float[3] ) { 0.7792693376541138, -0.1481880098581314, -0.6682907938957214 }, 0.260773732106438 },
	{ ( float[3] ) { 0.7740137577056885, -0.4785677492618561, -0.6698790192604065 }, 0.1989811319156961 },
	{ ( float[3] ) { 0.23285600543022156, -0.5073661208152771, -0.6738042831420898 }, 0.26669476451084984 },
	{ ( float[3] ) { 0.7247136235237122, 1.0682967901229858, 1.6127680540084839 }, 0.37319962502985937 },
	{ ( float[3] ) { 1.0770543813705444, -0.48595550656318665, -0.669867753982544 }, 0.2815689665792911 },
	{ ( float[3] ) { 0.6677731275558472, 1.9465017318725586, 1.471212387084961 }, 0.46395125521417857 },
	{ ( float[3] ) { 0.5216609835624695, -0.4932655692100525, -0.6708555221557617 }, 0.19644942665908222 },
	{ ( float[3] ) { 0.10963167995214462, 2.8734147548675537, 1.4728350639343262 }, 0.4454061070161991 },
	{ ( float[3] ) { 0.59532231092453, 1.4277867078781128, 1.8765215873718262 }, 0.4616079395342125 },
	{ ( float[3] ) { 1.335516333580017, 1.7082738876342773, 2.463707208633423 }, 0.49725006311592085 },
	{ ( float[3] ) { 0.48408299684524536, -0.01694926992058754, -0.6691303253173828 }, 0.27265150538141175 },
	{ ( float[3] ) { 1.1454806327819824, 1.0215739011764526, 1.5859087705612183 }, 0.413381270300842 },
	{ ( float[3] ) { 0.9263871312141418, 1.0234637260437012, 0.9825153946876526 }, 0.45965445522277226 },
	{ ( float[3] ) { 0.4836525022983551, 1.2569681406021118, 1.3914368152618408 }, 0.43632951980338686 },
	{ ( float[3] ) { 1.4257148504257202, -0.31740233302116394, -0.66749107837677 }, 0.2851084489692195 },
	{ ( float[3] ) { 0.3987450897693634, -0.6701739430427551, -0.6740431785583496 }, 0.1951394653315921 },
	{ ( float[3] ) { 0.5513759255409241, 0.9118250012397766, 0.9755812883377075 }, 0.3290337120976782 },
	{ ( float[3] ) { 0.44229069352149963, 0.9116331338882446, 1.331676721572876 }, 0.31348645657468277 },
	{ ( float[3] ) { 0.6919499635696411, 0.34282204508781433, -0.6722375154495239 }, 0.29888851570073066 },
	{ ( float[3] ) { 0.20692797005176544, -0.20459681749343872, -0.6704773306846619 }, 0.31620328564082706 },
	{ ( float[3] ) { 0.6656701564788818, 1.3324306011199951, 0.897783100605011 }, 0.37730175175703057 },
	{ ( float[3] ) { 0.16744232177734375, 0.8780773878097534, 0.8929876089096069 }, 0.5260977594315411 },
	{ ( float[3] ) { 1.5976922512054443, 2.475977659225464, 2.039844274520874 }, 0.5756102914143071 },
	{ ( float[3] ) { -0.00664945226162672, 2.4145171642303467, 1.339908480644226 }, 0.32229626789279325 },
	{ ( float[3] ) { 0.09978076070547104, 2.086571216583252, 1.7006837129592896 }, 0.47352382039129154 },
	{ ( float[3] ) { 0.1319900006055832, 1.066936731338501, 1.113855242729187 }, 0.39580835692068456 },
	{ ( float[3] ) { 1.578305721282959, 1.930254340171814, 1.8920849561691284 }, 0.6770844225164634 },
	{ ( float[3] ) { 2.0716934204101562, 2.117871046066284, 2.6291556358337402 }, 0.6181274751223393 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
